[package]

name = "gfx_debug_draw"
version = "0.11.1"
authors = ["Steve Jahns <s.t.jahns@gmail.com>"]
keywords = ["draw", "gfx", "debug", "piston"]
description = "Debug rendering library for gfx-rs"
license = "MIT"
readme = "README.md"
repository = "https://github.com/PistonDevelopers/gfx-debug-draw"
homepage = "https://github.com/PistonDevelopers/gfx-debug-draw"

[lib]

name = "gfx_debug_draw"
path = "src/lib.rs"

[dependencies]

gfx = "0.12.1"
gfx_text = "0.13.1"
vecmath = "0.2.0"

###### For example ###########################

[dev-dependencies]

piston = "0.26.0"
piston_window = "0.57.0"
sdl2 = "0.24.0"
pistoncore-sdl2_window = "0.36.0"
gfx_device_gl = "0.11.2"
shader_version = "0.2.1"
camera_controllers = "0.17.0"
current = "0.1.2"

###############################################
